name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install opencv
      run: sudo apt-get install libopencv-dev libpipewire-0.3-dev
    - name: comfigure
      run: cmake -B build
    - name: build
      run: cmake --build build
